map_frame: "map"
sensor_frame: "zed_camera_link"
robot_frame: "zed_camera_link"

m_resolution: 0.05
m_occupancy_min_thresh: 0.12
m_occupancy_max_thresh: 0.97

s_max_z: 2.0
s_min_z: -2.0
s_max_range: 5.0
s_min_range: 0.5
s_probability_hit: 0.7
s_probability_miss: 0.4

c_chunk_dim: 64 
c_chunk_folder_path: "Rolling-Bonxai/chunks"

use_sor_filter: false

viz_occupied: true
viz_free: false
viz_chunks: true
viz_usage: false